version: "3.4"
services:
  dmicrog:
    image: dmicrog:v0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MICRO_SERVER_ADDRESS: ":9099"
      MICRO_REGISTRY: consul
      MICRO_REGISTRY_ADDRESS: consul:8500
      MICRO_BROKER: kafka
      MICRO_BROKER_ADDRESS: kafka:9092
      MICRO_LOG_LEVEL: debug
  consul:
    image: consul:1.8
    expose:
    - "8500"
    ports:
    - "8500:8500"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500"]
      interval: 5s
      timeout: 5s
      retries: 3
    hostname: "consul"
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    expose:
    - 9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    hostname: "kafka"
