// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/dmicrog.proto

package dmicrog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Dmicrog service

func NewDmicrogEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Dmicrog service

type DmicrogService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Dmicrog_StreamService, error)
}

type dmicrogService struct {
	c    client.Client
	name string
}

func NewDmicrogService(name string, c client.Client) DmicrogService {
	return &dmicrogService{
		c:    c,
		name: name,
	}
}

func (c *dmicrogService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Dmicrog.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dmicrogService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Dmicrog_StreamService, error) {
	req := c.c.NewRequest(c.name, "Dmicrog.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &dmicrogServiceStream{stream}, nil
}

type Dmicrog_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type dmicrogServiceStream struct {
	stream client.Stream
}

func (x *dmicrogServiceStream) Close() error {
	return x.stream.Close()
}

func (x *dmicrogServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *dmicrogServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *dmicrogServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *dmicrogServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Dmicrog service

type DmicrogHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Dmicrog_StreamStream) error
}

func RegisterDmicrogHandler(s server.Server, hdlr DmicrogHandler, opts ...server.HandlerOption) error {
	type dmicrog interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
	}
	type Dmicrog struct {
		dmicrog
	}
	h := &dmicrogHandler{hdlr}
	return s.Handle(s.NewHandler(&Dmicrog{h}, opts...))
}

type dmicrogHandler struct {
	DmicrogHandler
}

func (h *dmicrogHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.DmicrogHandler.Call(ctx, in, out)
}

func (h *dmicrogHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.DmicrogHandler.Stream(ctx, m, &dmicrogStreamStream{stream})
}

type Dmicrog_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type dmicrogStreamStream struct {
	stream server.Stream
}

func (x *dmicrogStreamStream) Close() error {
	return x.stream.Close()
}

func (x *dmicrogStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *dmicrogStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *dmicrogStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *dmicrogStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}
